# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1cc8ae2d850103626cb73271971bc9130e57eb81bfa25bda2368e805c65a7f33f874cf6476f86130823460ef5e5d44922160f6e4531c69bf12761bf83f5f8634

test:
  secret_key_base: 70d06e2281836900300016b2667f515f09604f03ee86690bb5a6b6f16e86f152679d3b1ba6b3bed22f22514df6fa64200133df4fa376f5d9c7e1c9fc7720478a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
